Changed wrapper to discriminate by sockfds

diff --git a/util/mw_copy_to_pvm b/util/mw_copy_to_pvm
--- a/util/mw_copy_to_pvm
+++ b/util/mw_copy_to_pvm
@@ -1,6 +1,11 @@
 #!/bin/bash 
 
-PVM_IP=192.168.0.19
+
+if -z $PVM_IP; then
+   echo "Failure: PVM_IP must be defined in env"
+   exit 1
+fi
+
 PVM_USER=sluser
 MWROOT="$HOME/proj/mw-cbb"
 
