Renamed contentious Makefiles; added util scripts.
Run util/mw_prep to copy specific files so you can build.

diff --git a/util/mw_copy_to_pvm b/util/mw_copy_to_pvm
--- a/util/mw_copy_to_pvm
+++ b/util/mw_copy_to_pvm
@@ -5,8 +5,17 @@ if [ -z $PVM_IP ]; then
    exit 1
 fi
 
+if [ -z $PVM_USER ]; then
+   echo "Failure: PVM_USER must be defined in env"
+   exit 1
+fi
+
+if [ -z $MWROOT ]; then
+   echo "Failure: MWROOT must be defined in env"
+   exit 1
+fi
+
 PVM_USER=sluser
-MWROOT="$HOME/proj/mw-cbb"
 
 docmd() {
    echo "Command: $*"
